version: '2'

services:
  nginx:
    build: ./containers/nginx
    # container_name: nginx
    ports:
      - 9000:80
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./logs:/var/log/nginx
      - ./src:/var/www/html
    depends_on:
      - webserver
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - skynet
    command: nginx -g "daemon off;"
    restart: always

  webserver:
    build: ./containers/${WEB_SERVER_TYPE}
    # container_name: webserver
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./src:/var/www/html
      - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
      - ./logs/php:/var/log/php
    networks: 
      - skynet
    restart: always
  db:
    build: ./containers/${DB_SERVER_TYPE}
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./logs/${DB_SERVER_TYPE}:/var/log/mysql
      - ./data/${DB_SERVER_TYPE}:/var/lib/mysql
      - ./data/backup:/backup
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - skynet
    restart: always
networks:
  skynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.1/24
